### ISSUE TITLE
roadmap

### ISSUE THREAD

**Issue by Niklp09** [Archtec-io/armor-skins-and-wielditems#2]
- [x] implement skinned 1st person view hand (very difficult)
- [x] disallow invisible armor in armor_stands
- [x] combine wield3d and wieldview
- [x] redo customskins
- [x] invisible shields
- [x] merge upstream 3d_armor
- [x] see skin in player preview
- [x] fix skin preview in editor

**Comment by Niklp09** [comment]
yay everything is done :)

**Comment by Niklp09** [comment]
- [ ] redo wield3d or something else
